/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesRespiteCareRouteImport } from './routes/services.respite-care'
import { Route as ServicesPersonalCareRouteImport } from './routes/services.personal-care'
import { Route as ServicesLiveInCareRouteImport } from './routes/services.live-in-care'
import { Route as ServicesCompanionshipCareRouteImport } from './routes/services.companionship-care'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRespiteCareRoute = ServicesRespiteCareRouteImport.update({
  id: '/services/respite-care',
  path: '/services/respite-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPersonalCareRoute = ServicesPersonalCareRouteImport.update({
  id: '/services/personal-care',
  path: '/services/personal-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLiveInCareRoute = ServicesLiveInCareRouteImport.update({
  id: '/services/live-in-care',
  path: '/services/live-in-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCompanionshipCareRoute =
  ServicesCompanionshipCareRouteImport.update({
    id: '/services/companionship-care',
    path: '/services/companionship-care',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/team': typeof TeamRoute
  '/services/companionship-care': typeof ServicesCompanionshipCareRoute
  '/services/live-in-care': typeof ServicesLiveInCareRoute
  '/services/personal-care': typeof ServicesPersonalCareRoute
  '/services/respite-care': typeof ServicesRespiteCareRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/team': typeof TeamRoute
  '/services/companionship-care': typeof ServicesCompanionshipCareRoute
  '/services/live-in-care': typeof ServicesLiveInCareRoute
  '/services/personal-care': typeof ServicesPersonalCareRoute
  '/services/respite-care': typeof ServicesRespiteCareRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/team': typeof TeamRoute
  '/services/companionship-care': typeof ServicesCompanionshipCareRoute
  '/services/live-in-care': typeof ServicesLiveInCareRoute
  '/services/personal-care': typeof ServicesPersonalCareRoute
  '/services/respite-care': typeof ServicesRespiteCareRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/team'
    | '/services/companionship-care'
    | '/services/live-in-care'
    | '/services/personal-care'
    | '/services/respite-care'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/team'
    | '/services/companionship-care'
    | '/services/live-in-care'
    | '/services/personal-care'
    | '/services/respite-care'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/team'
    | '/services/companionship-care'
    | '/services/live-in-care'
    | '/services/personal-care'
    | '/services/respite-care'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  TeamRoute: typeof TeamRoute
  ServicesCompanionshipCareRoute: typeof ServicesCompanionshipCareRoute
  ServicesLiveInCareRoute: typeof ServicesLiveInCareRoute
  ServicesPersonalCareRoute: typeof ServicesPersonalCareRoute
  ServicesRespiteCareRoute: typeof ServicesRespiteCareRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/respite-care': {
      id: '/services/respite-care'
      path: '/services/respite-care'
      fullPath: '/services/respite-care'
      preLoaderRoute: typeof ServicesRespiteCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/personal-care': {
      id: '/services/personal-care'
      path: '/services/personal-care'
      fullPath: '/services/personal-care'
      preLoaderRoute: typeof ServicesPersonalCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/live-in-care': {
      id: '/services/live-in-care'
      path: '/services/live-in-care'
      fullPath: '/services/live-in-care'
      preLoaderRoute: typeof ServicesLiveInCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/companionship-care': {
      id: '/services/companionship-care'
      path: '/services/companionship-care'
      fullPath: '/services/companionship-care'
      preLoaderRoute: typeof ServicesCompanionshipCareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  TeamRoute: TeamRoute,
  ServicesCompanionshipCareRoute: ServicesCompanionshipCareRoute,
  ServicesLiveInCareRoute: ServicesLiveInCareRoute,
  ServicesPersonalCareRoute: ServicesPersonalCareRoute,
  ServicesRespiteCareRoute: ServicesRespiteCareRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
